paths:
  boundary_conditions: D:\GFM\inputs  # original: 'p:/11210264-004-global-flood-modellin/Boundary_conditions'
  processed_inputs: D:\GFM\processed_inputs  # original: 'p:/11210264-004-global-flood-modellin/Boundary_conditions/processed_waterlevels'
  MDT_correction_file: D:\GFM\inputs\Aviso\mdt_hybrid_cnes_cls22_cmems2020_global.nc  # original: 'p:/11210264-004-global-flood-modellin/Boundary_conditions/MDT_and_MSS/dataset-mdt-hybrid-cnes-cls22-cmems2020-global_1719842140172.nc'
  SLR_directory: D:\GFM\inputs\SLR\ar6-regional-confidence\regional\confidence_output_files\medium_confidence  # original: 'p:/11210264-004-global-flood-modellin/Boundary_conditions/SLR/ar6-regional-confidence/ar6-regional-confidence/regional/confidence_output_files'
  WL_scenarios: D:\GFM\processed_inputs\WL_scenarios

  hydromt_lib: "C:/Users/Schlu005/GFM/python/config/data_catalog_gfm.yml"
  domain_mask: D:\GFM\domain_masks\test_domains_hybas_lvl2_africa.gpkg # test domain.
  masks: D:\GFM\domain_masks\masks
  run_output: D:\GFM\model_outputs
  tile_mask_grid: D:\GFM\inputs\mask\tiles_2_5deg_overlap.gpkg

choices:
  SLR_scenario: "ssp245"  # options are: ["ssp126", "ssp245", "ssp585"]
  confidence_level: "medium"  # options are: ["low", "medium"]