"""Run the Aqueduct flood model for a single tile/return_period/waterlevel_name,
from a plain CLI call instead of a Snakemake `script:` invocation.

Used by the sbatch scripts generated by generate_aqueduct_jobs.py, one call
per (tile_id, return_period, waterlevel_name) - see that script and
hpc_dispatch.smk's generate_aqueduct_jobs rule for context. Reuses the exact
same skip/OOM-catch/placeholder logic as scripts/run_aqueduct.py; the only
difference is that jobs whose boundaries were already found empty are
filtered out at generation time (on the Windows preprocessing machine, which
has that file available), so this script only needs to handle the OOM case,
which can only be discovered by actually invoking the executable.

Usage:
    python run_aqueduct_cli.py --config <resolved_config.yml>
        --tile-id <id> --return-period <RP..> --waterlevel-name <SLR_..>
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from aqueduct_runner import is_oom_error, log_skipped_tile, mark_tile_oom, run_aqueduct, tile_marked_oom  # noqa: E402
from rasters import save_nodata_raster  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", required=True, help="Path to a fully-resolved config.yml (e.g. resolved_config.yml)")
    parser.add_argument("--tile-id", required=True)
    parser.add_argument("--return-period", required=True)
    parser.add_argument("--waterlevel-name", required=True)
    args = parser.parse_args()

    with open(args.config, encoding="utf-8") as f:
        config = yaml.safe_load(f)

    model_outputs = config["simulation"]["model_outputs"]
    aqueduct_executable = config["simulation"]["aqueduct_executable"]
    raster_config = config["raster_format"]

    tile_id = args.tile_id
    scenario_name = f"{args.return_period}_{args.waterlevel_name}"
    tile_dir = os.path.join(model_outputs, tile_id)
    toml_path = os.path.join(tile_dir, "inputs", f"aqueduct_{scenario_name}.toml")
    dem_path = os.path.join(tile_dir, "inputs", "dem.tif")
    output_path = os.path.join(tile_dir, "results", f"waterdepth_{scenario_name}.tif")
    skipped_dir = os.path.join(model_outputs, "skipped_tiles")
    oom_dir = os.path.join(model_outputs, "oom_tiles")

    if tile_marked_oom(oom_dir, tile_id):
        log_skipped_tile(
            skipped_dir, tile_id, scenario_name,
            reason="tile too large for Aqueduct (OutOfMemoryError on a previous return period/SLR scenario for this tile)",
        )
        save_nodata_raster(dem_path, output_path, raster_config)
        return

    try:
        run_aqueduct(aqueduct_executable, toml_path)
    except subprocess.CalledProcessError as e:
        if not is_oom_error(e):
            raise
        mark_tile_oom(oom_dir, tile_id, reason="OutOfMemoryError in component_indices (core.jl) - tile too large for Aqueduct")
        log_skipped_tile(skipped_dir, tile_id, scenario_name, reason="OutOfMemoryError - tile too large for Aqueduct")
        save_nodata_raster(dem_path, output_path, raster_config)


if __name__ == "__main__":
    main()
