"""Run the flood model for a single tile/return_period/waterlevel_name,
from a plain CLI call instead of a Snakemake `script:` invocation.

Used by the sbatch scripts generated by generate_aqueduct_jobs.py, one call
per (tile_id, return_period, waterlevel_name) - see that script and
hpc_dispatch.smk's generate_aqueduct_jobs rule for context. Reuses the exact
same skip/OOM-catch/placeholder logic as scripts/run_aqueduct.py; the only
difference is that wave-0 jobs whose boundaries were already found empty are
filtered out at generation time (on the Windows preprocessing machine, which
has that file available), so this script only needs to handle the OOM case
for wave-0 (which can only be discovered by actually invoking the model).
The wave>=1 (hop_distance >= 1) neighbour-seeding branch CANNOT be
pre-filtered the same way (it needs live neighbour-output data, not just
static tile geometry, so "no seeds yet" can only be discovered here) - see
`run_aqueduct.py`'s module docstring for the full wave-based-forcing
picture. Keep this in sync with run_aqueduct.py.

Usage:
    python run_aqueduct_cli.py --config <resolved_config.yml>
        --tile-id <id> --return-period <RP..> --waterlevel-name <SLR_..>
"""

import argparse
import os
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from aqueduct_runner import (  # noqa: E402
    NO_UPSTREAM_FLOODING_REASON,
    log_skipped_tile,
    mark_tile_oom,
    run_aqueduct_python,
    tile_marked_oom,
    write_zero_waterdepth,
)
from boundaries import collect_neighbor_wave_seeds  # noqa: E402
from config_utils import path_ready  # noqa: E402
from rasters import save_nodata_raster  # noqa: E402
from tiles import load_tile_grid  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", required=True, help="Path to a fully-resolved config.yml (e.g. resolved_config.yml)")
    parser.add_argument("--tile-id", required=True)
    parser.add_argument("--return-period", required=True)
    parser.add_argument("--waterlevel-name", required=True)
    args = parser.parse_args()

    with open(args.config, encoding="utf-8") as f:
        config = yaml.safe_load(f)

    model_outputs = config["simulation"]["model_outputs"]
    raster_config = config["raster_format"]
    flooding_config = config["simulation"]["flooding"]
    ocean_code = config["tile_generation"]["ocean_code"]
    river_code = config["tile_generation"]["river_code"]
    tile_grid_path = config["tile_grid"]["path"]

    tile_id = args.tile_id
    scenario_name = f"{args.return_period}_{args.waterlevel_name}"
    tile_dir = os.path.join(model_outputs, tile_id)
    inputs_dir = os.path.join(tile_dir, "inputs")
    dem_path = os.path.join(inputs_dir, "dem.tif")
    mask_path = os.path.join(inputs_dir, "mask.tif")
    friction_path = os.path.join(inputs_dir, "friction.tif")
    boundaries_path = os.path.join(inputs_dir, f"boundaries_{scenario_name}.gpkg")
    output_path = os.path.join(tile_dir, "results", f"waterdepth_{scenario_name}.tif")
    skipped_dir = os.path.join(model_outputs, "skipped_tiles")
    oom_dir = os.path.join(model_outputs, "oom_tiles")

    if tile_marked_oom(oom_dir, tile_id):
        log_skipped_tile(
            skipped_dir, tile_id, scenario_name,
            reason="tile too large (out-of-memory on a previous return period/SLR scenario for this tile)",
        )
        save_nodata_raster(dem_path, output_path, raster_config)
        return

    tile_grid = load_tile_grid(tile_grid_path)
    this_tile = tile_grid[tile_grid["tile_id"] == int(tile_id)]
    hop_distance = int(this_tile["hop_distance"].iloc[0])

    # Wave-0 jobs with no COAST-RP stations are filtered out at generation
    # time (see module docstring), so boundaries_path is only ever passed
    # through unread here - the hop>=1 branch below resolves its own
    # forcing directly from neighbour output instead.
    seed_rows = seed_cols = seed_values = None
    if hop_distance >= 1:
        this_geom = this_tile.geometry.iloc[0]
        candidates = tile_grid[
            (tile_grid["hop_distance"] < hop_distance)
            & (tile_grid["tile_id"] != int(tile_id))
            & tile_grid.geometry.intersects(this_geom)
        ]
        available = []
        for cand_id in candidates["tile_id"]:
            cand_dem = os.path.join(model_outputs, str(int(cand_id)), "inputs", "dem.tif")
            cand_mask = os.path.join(model_outputs, str(int(cand_id)), "inputs", "mask.tif")
            cand_waterdepth = os.path.join(
                model_outputs, str(int(cand_id)), "results", f"waterdepth_{scenario_name}.tif",
            )
            # path_ready, not bare os.path.exists (which swallows I/O errors
            # and returns False without ever retrying) - on the HPC's
            # network-mounted P:\ share, a transient blip here would
            # otherwise be silently indistinguishable from "neighbour
            # genuinely hasn't run yet", converting into a wrongly-confident
            # real-zero result instead of the correct flooded one.
            if path_ready(cand_dem) and path_ready(cand_mask) and path_ready(cand_waterdepth):
                available.append((cand_dem, cand_mask, cand_waterdepth))
        seed_rows, seed_cols, seed_values = collect_neighbor_wave_seeds(dem_path, available)
        if len(seed_rows) == 0:
            log_skipped_tile(skipped_dir, tile_id, scenario_name, reason=NO_UPSTREAM_FLOODING_REASON)
            write_zero_waterdepth(dem_path, output_path)
            return

    oc_config = flooding_config.get("obstacle_coupling", {})
    try:
        run_aqueduct_python(
            dem_path, mask_path, friction_path, output_path,
            resolution=flooding_config["resolution"], k=flooding_config["knn"],
            variable=args.waterlevel_name,
            boundaries_path=None if hop_distance >= 1 else boundaries_path,
            seed_rows=seed_rows, seed_cols=seed_cols, seed_values=seed_values,
            ocean_code=ocean_code, river_code=river_code,
            obstacle_coupling=oc_config.get("enabled", False),
            max_outer_iterations=oc_config.get("max_outer_iterations", 5),
            max_rounds=flooding_config["max_rounds"],
            outer_convergence_pct=oc_config.get("outer_convergence_pct", 0.01),
            waterlevel_epsilon_m=flooding_config["waterlevel_epsilon_m"],
        )
    except MemoryError:
        mark_tile_oom(oom_dir, tile_id, reason="MemoryError in flood_depth_dense - tile too large")
        log_skipped_tile(skipped_dir, tile_id, scenario_name, reason="MemoryError - tile too large")
        save_nodata_raster(dem_path, output_path, raster_config)


if __name__ == "__main__":
    main()
